---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: apis-auto-register
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: pkgi
    kapp.k14s.io/change-rule.0: "upsert after upserting pkgr"
    kapp.k14s.io/change-rule.1: "delete before deleting pkgr"
spec:
  serviceAccountName: tap-install-sa
  packageRef:
    refName: apis.apps.tanzu.vmware.com
    versionSelection:
      constraints: 0.3.3
      prereleases: {}
