#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
---
apiVersion: v1
kind: Secret
metadata:
  name: full-tbs-deps-values
  namespace: tap-install
stringData:
  values.yaml: |
    kp_default_repository: "tapazreg.azurecr.io/tap174-images/full-deps-package-repo"