---
secrets:
  eso:
    vault:
      server: http://vault.lab.tapmedas.com:8200
      namespace: ""
      auth:
        kubernetes:
          mountPath: tapazrun
          role: tapazrun--tanzu-sync-secrets
    remote_refs:
      sync_git:
        # TODO: Fill in your configuration for ssh or basic auth here (see tanzu-sync/app/config/.tanzu-managed/schema--eso.yaml)
        ssh:  
          private_key:
            key: secret/dev/tapazfull/tanzu-sync/sync-git/ssh
            property: privatekey
          known_hosts:
            key: secret/dev/tapazfull/tanzu-sync/sync-git/ssh
            property: knownhosts
      install_registry_dockerconfig:
        dockerconfigjson:
          key: secret/dev/tapazrun/tanzu-sync/install-registry-dockerconfig
