tap_install:
  values:
    profile: full
    ceip_policy_disclosed: true
    # Tanzu Application Platform values go here.

    contour:
      envoy:
        service:
          type: LoadBalancer
    shared:
      ingress_domain: "tapmedas.com"
#      ingress_issuer: "selfsigned-cluster-issuer"
      image_registry:
        project_path: "tapazreg.azurecr.io/tap163-build"

    supply_chain: basic

    namespace_provisioner:
      controller: false
      default_parameters:
        limits:
          default:
            cpu: 1.7
            memory: 1Gi
          defaultRequest:
            cpu: 100m
            memory: 1Gi
      gitops_install:
        ref: origin/main
        subPath: ns-provisioner-samples/gitops-install
        url: https://github.com/vmware-tanzu/application-accelerator-samples.git      

#    tap_gui:
#      ingressEnabled: "true"
#      ingressDomain: "tapmedas.com"
#      app_config:
#        auth:
#          allowGuestAccess: true      
#        app:
#          baseUrl: https://tap-gui.lab.tapmedas.com
#        catalog:
#          locations:
#            - type: url
#              target: https://github.com/sample-accelerators/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml
#        backend:
#          baseUrl: https://tap-gui.lab.tapmedas.com
#          cors:
#            origin: https://tap-gui.lab.tapmedas.com        
    
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    - api-portal.tanzu.vmware.com
    - accelerator.apps.tanzu.vmware.com
    - apiserver.appliveview.tanzu.vmware.com
    - local-source-proxy.apps.tanzu.vmware.com
    - tap-gui.tanzu.vmware.com
