tap_install:
  values:
    profile: full
    ceip_policy_disclosed: true
    # Tanzu Application Platform values go here.

    contour:
      envoy:
        service:
          type: LoadBalancer
    shared:
      ingress_domain: "tapmedas.com"
#      ingress_issuer: "selfsigned-cluster-issuer"
      image_registry:
        project_path: "tapazreg.azurecr.io/tap163-build"
## testing commit
#    supply_chain: testing
#    supply_chain: basic
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      external_delivery: true
      image_scanner_template_name: image-vulnerability-scan-trivy
      image_scanning_cli:
        image: aquasec/trivy:0.42.1
      gitops:
        deliverable_repository_owner: "dasbatta"
        deliverable_repository_name: "tap-delivery_repo"
        deliverable_branch: main
        deliverable_server_address: "ssh://git@github.com"
        ssh_secret: "git-auth"
        server_address: "ssh://git@github.com"
        repository_owner: "dasbatta"
        repository_name: "tap-gitops-config"
        branch: main
    metadata_store:
      amr:
        deploy: true    
    amr: 
      deploy_observer: true
      observer:
        location: |
          labels:
          - key: environment
            value: test
        resync_period: "5h"
        eventhandler:
          endpoint: "https://amr-persister.view.tapmedas.com"
          liveness_period_seconds: 25
        ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDHzCCAgegAwIBAgIRAM+F+5fzyZzukbVQrJ4/24swDQYJKoZIhvcNAQELBQAw
          KTEnMCUGA1UEAxMedGFwLWluZ3Jlc3Mtc2VsZnNpZ25lZC1yb290LWNhMB4XDTI0
          MDEzMDA1MTA1NloXDTI0MDQyOTA1MTA1NlowKTEnMCUGA1UEAxMedGFwLWluZ3Jl
          c3Mtc2VsZnNpZ25lZC1yb290LWNhMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
          CgKCAQEA4vLhV2WUTT5rayDR1SqxMtqhK65Xp/biwwFniHT5+ND6OULQXqQ7hjUz
          dXu1x+aSlIDBY97nqVTKoba85pH3VIoiPT6zuOfTsO5yIkWo2dYCndzicQzvCKEN
          jY8mAdkZtXtQ+W1y/AaLB8qAZXMW6UfgOSWHB0zmt71QUNTUX87MiyPEHCIXpHIn
          rOYV+xRRnPxTMYGC4AUP9WT4RT6XohAsTnJK1mSYySFw4jBVuDkvosF/IgmLQuBj
          dKz5vjB3R7Kr6mpUHCTUlkWSwmm0FVJRdPX3tBR9cnylZWVQKnb1RJThVVgsIy+W
          +xdgepB3dnsrVjCTK9wP/lJNVYSDHwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQw
          DwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUGFhCqUguug+T3Z4kyhbZUdBVKC8w
          DQYJKoZIhvcNAQELBQADggEBACt+eUt1fj3BCoUTPAAw0Gblb/Kx5A3DCOxRElwj
          4TQFglqs3VR0A5s204B7mEIq7EZU3+vKVX9RjIVv1EaifTCfTHvc2Fpt0rTOW1uW
          +PlieUbAfEzzYTEwl/RBK/9ZoOFUBU67OgHsXXl9vOTJkklcKsVU2xHyNCtO4sVd
          foEZbgf5yC1K4bjbwQdFSwlhZWHqnUk/z7iiPAeQn5rsYQhLfYXUupfM3i3XSFGz
          2YPjnOsIbil38u4GB+QVvEML8SGdQqmHBBsiZkOX/AJso7VMh91bOKOvnsXUUuEM
          eBAa5mK2C/I519xzX+0RejnGi5VX8TmJ3y00t7jw7A1cKjA=
          -----END CERTIFICATE-----
## testing    
#   grype:
#      namespace: dev-test
#      targetImagePullSecret: "registries-credentials"
#      metadataStore:
#         url: "https://metadata-store.view.tapmedas.com"
#         caSecret:
#           name: store-ca-cert
#           importFromNamespace: metadata-store-secrets
#         authSecret:
#           name: store-auth-token
#           importFromNamespace: metadata-store-secrets

    scanning:
      metadataStore:
        url: ""
    namespace_provisioner:
      import_data_values_secrets:
      - name: tenant-secrets
        namespace: tap-install
        create_export: true
      controller: false
      default_parameters:
        limits:
          default:
            cpu: 1.7
            memory: 1Gi
          defaultRequest:
            cpu: 100m
            memory: 1Gi
      gitops_install:
        # ref: origin/main
        # subPath: ns-provisioner-samples/gitops-install
        # url: https://github.com/vmware-tanzu/application-accelerator-samples.git
        url: ssh://git@github.com/dasbatta/tap162-gitops-azvault
        ref: origin/daswork
        subPath: namespaces
        secretRef:
          name: sync-git
          namespace: tanzu-sync  
          create_export: true    
      additional_sources:
      - git:
          url: ssh://git@github.com/dasbatta/tap162-gitops-azvault
          ref: origin/daswork
          subPath: gitcred
          secretRef:
            name: sync-git
            namespace: tanzu-sync
            create_export: true
        path: _ytt_lib/workload-creds
      overlay_secrets:
      - name: workload-git-ssh-overlay
        namespace: tap-install
        create_export: true
#    tap_gui:
#      ingressEnabled: "true"
#      ingressDomain: "tapmedas.com"
#      app_config:
#        auth:
#          allowGuestAccess: true      
#        app:
#          baseUrl: https://tap-gui.lab.tapmedas.com
#        catalog:
#          locations:
#            - type: url
#              target: https://github.com/sample-accelerators/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml
#        backend:
#          baseUrl: https://tap-gui.lab.tapmedas.com
#          cors:
#            origin: https://tap-gui.lab.tapmedas.com        
    
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    - api-portal.tanzu.vmware.com
    - local-source-proxy.apps.tanzu.vmware.com
    - tap-gui.tanzu.vmware.com
    package_overlays:
    - name: "ootb-supply-chain-testing-scanning"
      secrets: 
      - name: "ootb-supply-chain-overlay"
    - name: "ootb-templates"
      secrets: 
      - name: "ootb-template-overlay"
    api_auto_registration:
      tap_gui_url: https://tap-gui.view.tapmedas.com
      cluster_name: tapazview
    

