tap_install:
  values:
    profile: full
    ceip_policy_disclosed: true
    # Tanzu Application Platform values go here.

    contour:
      envoy:
        service:
          type: LoadBalancer
    shared:
      ingress_domain: "tapmedas.com"
#      ingress_issuer: "selfsigned-cluster-issuer"
      image_registry:
        project_path: "tapazreg.azurecr.io/tap163-build"
## testing commit
#    supply_chain: testing
#    supply_chain: basic
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      external_delivery: true
      image_scanner_template_name: image-vulnerability-scan-trivy
      image_scanning_cli:
        image: aquasec/trivy:0.42.1
      gitops:
        deliverable_repository_owner: "dasbatta"
        deliverable_repository_name: "tap-delivery_repo"
        deliverable_branch: main
        deliverable_server_address: "ssh://git@github.com"
        ssh_secret: "git-auth"
        server_address: "ssh://git@github.com"
        repository_owner: "dasbatta"
        repository_name: "tap-gitops-config"
        branch: main
    metadata_store:
      amr:
        deploy: true    
    amr: 
      deploy_observer: true
      observer:
        location: |
          labels:
          - key: environment
            value: test
        resync_period: "5h"
        eventhandler:
          endpoint: "https://amr-persister.view.tapmedas.com"
          liveness_period_seconds: 25
        ca_cert_data: |
          -----BEGIN CERTIFICATE-----
          MIIDHjCCAgagAwIBAgIQL85Un3sVM856+mkAzkq51jANBgkqhkiG9w0BAQsFADAp
          MScwJQYDVQQDEx50YXAtaW5ncmVzcy1zZWxmc2lnbmVkLXJvb3QtY2EwHhcNMjMx
          MjAxMDUxMDU2WhcNMjQwMjI5MDUxMDU2WjApMScwJQYDVQQDEx50YXAtaW5ncmVz
          cy1zZWxmc2lnbmVkLXJvb3QtY2EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQDi8uFXZZRNPmtrINHVKrEy2qErrlen9uLDAWeIdPn40Po5QtBepDuGNTN1
          e7XH5pKUgMFj3uepVMqhtrzmkfdUiiI9PrO459Ow7nIiRajZ1gKd3OJxDO8IoQ2N
          jyYB2Rm1e1D5bXL8BosHyoBlcxbpR+A5JYcHTOa3vVBQ1NRfzsyLI8QcIhekcies
          5hX7FFGc/FMxgYLgBQ/1ZPhFPpeiECxOckrWZJjJIXDiMFW4OS+iwX8iCYtC4GN0
          rPm+MHdHsqvqalQcJNSWRZLCabQVUlF09fe0FH1yfKVlZVAqdvVElOFVWCwjL5b7
          F2B6kHd2eytWMJMr3A/+Uk1VhIMfAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwICpDAP
          BgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQYWEKpSC66D5PdniTKFtlR0FUoLzAN
          BgkqhkiG9w0BAQsFAAOCAQEALuczWpiccbu5n4I5Z3ESmqJ8WKxfWUphNR2ijMYc
          hvqSdAt9BKUhssPKEBqt1bl7amNQJIEEYSLdjEVLITC/wLyrEWq+y6FYXw2Tv+JT
          TdUWg4mwgmHwjuH4a8s8cb8+an+h34qlTwNpoAaP0nAz9S3mxxuF/yC/KzJAET7k
          VjZ8m2GBdrem016WH2gaJ/09ou+XeJqfSZdJWyuH5YpC/hTiHQ1HWg1KVf5IQODQ
          itfvj4uV8TLKZ8WEOV6s776oeru+5Ibi0maPp9ExV8gLhqGqUWqc36qfHouK13ty
          nUUgqhK0txjVDQ7im0o3uFiBJ8VM2XGykcRjyHAf1cJUpQ==
          -----END CERTIFICATE-----
    
#   grype:
#      namespace: dev-test
#      targetImagePullSecret: "registries-credentials"
#      metadataStore:
#         url: "https://metadata-store.view.tapmedas.com"
#         caSecret:
#           name: store-ca-cert
#           importFromNamespace: metadata-store-secrets
#         authSecret:
#           name: store-auth-token
#           importFromNamespace: metadata-store-secrets

    scanning:
      metadataStore:
        url: ""
    namespace_provisioner:
      import_data_values_secrets:
      - name: tenant-secrets
        namespace: tap-install
        create_export: true
      controller: false
      default_parameters:
        limits:
          default:
            cpu: 1.7
            memory: 1Gi
          defaultRequest:
            cpu: 100m
            memory: 1Gi
      gitops_install:
        # ref: origin/main
        # subPath: ns-provisioner-samples/gitops-install
        # url: https://github.com/vmware-tanzu/application-accelerator-samples.git
        url: ssh://git@github.com/dasbatta/tap162-gitops-azvault
        ref: origin/daswork
        subPath: namespaces
        secretRef:
          name: sync-git
          namespace: tanzu-sync  
          create_export: true    
      additional_sources:
      - git:
          url: ssh://git@github.com/dasbatta/tap162-gitops-azvault
          ref: origin/daswork
          subPath: gitcred
          secretRef:
            name: sync-git
            namespace: tanzu-sync
            create_export: true
        path: _ytt_lib/workload-creds
      overlay_secrets:
      - name: workload-git-ssh-overlay
        namespace: tap-install
        create_export: true
#    tap_gui:
#      ingressEnabled: "true"
#      ingressDomain: "tapmedas.com"
#      app_config:
#        auth:
#          allowGuestAccess: true      
#        app:
#          baseUrl: https://tap-gui.lab.tapmedas.com
#        catalog:
#          locations:
#            - type: url
#              target: https://github.com/sample-accelerators/tanzu-java-web-app/blob/main/catalog/catalog-info.yaml
#        backend:
#          baseUrl: https://tap-gui.lab.tapmedas.com
#          cors:
#            origin: https://tap-gui.lab.tapmedas.com        
    
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    - api-portal.tanzu.vmware.com
    - apiserver.appliveview.tanzu.vmware.com
    - local-source-proxy.apps.tanzu.vmware.com
    - tap-gui.tanzu.vmware.com
    package_overlays:
    - name: "ootb-supply-chain-testing-scanning"
      secrets: 
      - name: "ootb-supply-chain-overlay"
    - name: "ootb-templates"
      secrets: 
      - name: "ootb-template-overlay"

