---
secrets:
  eso:
    vault:
      server: http://vault.lab.tapmedas.com:8200
      namespace: ""
      auth:
        kubernetes:
          mountPath: tapazfull
          role: tapazfull--tanzu-sync-secrets
    remote_refs:
      sync_git:
        ssh:
        private_key:
          key: secret/dev/tapazfull/tanzu-sync/sync-git/ssh
          property: privatekey
        known_hosts:
          key: secret/dev/tapazfull/tanzu-sync/sync-git/ssh
          property: knownhosts
      install_registry_dockerconfig:
        dockerconfigjson:
          key: secret/dev/tapazfull/tanzu-sync/install-registry-dockerconfig
